#!/usr/bin/env python

# from ctypes import *
from ctypes import Structure,c_uint16,c_double,c_ubyte,c_uint32,c_int16,c_char


RECOGNITION_CHANNEL_NAME = 'recognition'

# only need to send a char representing user input
class RECOGNITION_TYPE(Structure):
	_pack_ = 1
	_fields_ = [("key",    c_double),
                    ("count",  c_double),
		    ("detectionID0", c_uint32),
		    ("detectionID1", c_uint32),
		    ("detectionID2", c_uint32),
		    ("detectionID3", c_uint32),
		    ("detectionID4", c_uint32),
		    ("detectionID5", c_uint32),
		    ("detectionID6", c_uint32),
		    ("detectionID7", c_uint32),
		    ("detectionX0", c_double),
		    ("detectionX1", c_double),
		    ("detectionX2", c_double),
		    ("detectionX3", c_double),
		    ("detectionX4", c_double),
		    ("detectionX5", c_double),
		    ("detectionX6", c_double),
		    ("detectionX7", c_double),
		    ("detectionY0", c_double),
		    ("detectionY1", c_double),
		    ("detectionY2", c_double),
		    ("detectionY3", c_double),
		    ("detectionY4", c_double),
		    ("detectionY5", c_double),
		    ("detectionY6", c_double),
		    ("detectionY7", c_double),
		    ("detectionZ0", c_double),
		    ("detectionZ1", c_double),
		    ("detectionZ2", c_double),
		    ("detectionZ3", c_double),
		    ("detectionZ4", c_double),
		    ("detectionZ5", c_double),
		    ("detectionZ6", c_double),
		    ("detectionZ7", c_double),
		    ("detectionTHETA0", c_double),
		    ("detectionTHETA1", c_double),
		    ("detectionTHETA2", c_double),
		    ("detectionTHETA3", c_double),
		    ("detectionTHETA4", c_double),
		    ("detectionTHETA5", c_double),
		    ("detectionTHETA6", c_double),
		    ("detectionTHETA7", c_double),
		    ("detectionPITCH0", c_double),
		    ("detectionPITCH1", c_double),
		    ("detectionPITCH2", c_double),
		    ("detectionPITCH3", c_double),
		    ("detectionPITCH4", c_double),
		    ("detectionPITCH5", c_double),
		    ("detectionPITCH6", c_double),
		    ("detectionPITCH7", c_double),
		    ("detectionROLL0", c_double),
		    ("detectionROLL1", c_double),
		    ("detectionROLL2", c_double),
		    ("detectionROLL3", c_double),
		    ("detectionROLL4", c_double),
		    ("detectionROLL5", c_double),
		    ("detectionROLL6", c_double),
		    ("detectionROLL7", c_double)]
